# Generated by Django 3.2.8 on 2021-10-26 18:16

import Location.snippets
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Названия вида деятельности')),
            ],
            options={
                'verbose_name_plural': 'Виды деятельности',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Location.snippets.name_of_file, verbose_name='Фото специалиста')),
                ('description', models.CharField(max_length=500)),
                ('is_deactivated', models.BooleanField(default=False, verbose_name='Скрыть карточку специалиста')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialistApp.category', verbose_name='Вид деятельности специалиста')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_specialist', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт специалиста')),
            ],
            options={
                'verbose_name_plural': 'Специалист',
            },
        ),
    ]
