# Generated by Django 3.2.8 on 2021-10-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='category',
        ),
        migrations.AddField(
            model_name='specialist',
            name='category',
            field=models.ManyToManyField(to='specialistApp.Category', verbose_name='Вид деятельности специалиста'),
        ),
    ]
