# Generated by Django 3.2.8 on 2021-11-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0003_remove_location_category'),
        ('specialistApp', '0002_auto_20211027_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locationApp.location', verbose_name='Локация специалиста'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialist',
            name='category',
            field=models.ManyToManyField(to='specialistApp.Category', verbose_name='Виды деятельности специалиста'),
        ),
    ]
