# Generated by Django 3.2.8 on 2021-11-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0003_remove_location_category'),
        ('specialistApp', '0003_auto_20211102_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='locationApp.location', verbose_name='Локация специалиста'),
        ),
    ]
