# Generated by Django 3.2.8 on 2021-11-25 13:25

import Location.snippets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0004_alter_specialist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Asd', max_length=500, verbose_name='Описание для вида деятельности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='ASD', upload_to=Location.snippets.name_of_file, verbose_name='Фото специалиста'),
            preserve_default=False,
        ),
    ]
