# Generated by Django 3.2.8 on 2021-12-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0005_auto_20211125_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
