# Generated by Django 3.2.8 on 2022-05-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0011_alter_location_category_location'),
        ('specialistApp', '0006_alter_specialist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='custom_location',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Ручная локация'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='locationApp.location', verbose_name='Локация специалиста'),
        ),
    ]
