# Generated by Django 3.2.8 on 2022-06-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planApp', '0001_initial'),
        ('specialistApp', '0008_alter_specialist_is_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='planApp.plan', verbose_name='Тариф специалиста'),
        ),
    ]
