# Generated by Django 3.2.8 on 2021-11-24 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0003_remove_location_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialistApp', '0003_auto_20211102_1334'),
        ('commentApp', '0002_auto_20211124_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationApp.location'),
        ),
        migrations.AlterField(
            model_name='reviewlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь оставивший оценку'),
        ),
        migrations.AlterField(
            model_name='reviewspecialist',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='specialistApp.specialist'),
        ),
        migrations.AlterField(
            model_name='reviewspecialist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь оставивший оценку'),
        ),
    ]
