# Generated by Django 3.2.8 on 2021-12-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0004_alter_reviewlocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlocation',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentspecialist',
            name='comment',
            field=models.TextField(),
        ),
    ]
