# Generated by Django 3.2.8 on 2021-12-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0005_auto_20211218_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlocation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentspecialist',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
