# Generated by Django 3.2.8 on 2021-12-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0005_auto_20211125_2351'),
        ('commentApp', '0006_auto_20211220_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='locationApp.location'),
        ),
    ]
