# Generated by Django 3.2.8 on 2022-08-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialistApp', '0009_specialist_plan'),
        ('planApp', '0002_plan_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='specialistApp.specialist')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_plan', to='planApp.plan')),
            ],
        ),
        migrations.CreateModel(
            name='OrderUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.BigIntegerField()),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_unique', to='paymentApp.orderuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('bindingId', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='paymentApp.orderuser')),
            ],
        ),
    ]
