# Generated by Django 3.2.8 on 2022-08-10 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0009_specialist_plan'),
        ('paymentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='specialistApp.specialist'),
        ),
        migrations.AlterField(
            model_name='orderunique',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_unique', to='specialistApp.specialist'),
        ),
        migrations.DeleteModel(
            name='OrderUser',
        ),
    ]
