# Generated by Django 3.2.8 on 2022-08-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0003_orderstatus_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='days',
        ),
    ]
