# Generated by Django 3.2.8 on 2022-08-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0004_remove_orderstatus_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='bindingId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
