<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class TenderFile extends Model
{
    const UPLOAD_DIRECTORY = 'uploads/tenders/';

    protected $fillable = [
        'path'
    ];

    public function delete()
    {
        if ($this->path) {
            Storage::delete(self::UPLOAD_DIRECTORY . $this->path);
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function getFileUrl()
    {

        if ($this->path) {
            $regex = '/^(http|https):\\/\\/[a-z0-9_]+([\\-\\.]{1}[a-z_0-9]+)*\\.[_a-z]{2,5}' . '((:[0-9]{1,5})?\\/.*)?$/i';
            $remove_space = str_replace(" ", "", $this->path);
            if (preg_match(
                "$regex", $remove_space)) {
                return $remove_space;
            }
            return url('/' . self::UPLOAD_DIRECTORY . $this->path);
        }
        return '';
    }

}
