# Generated by Django 3.2.8 on 2022-01-09 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phoneApp', '0002_alter_phoneverifier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverifier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_validation', to=settings.AUTH_USER_MODEL),
        ),
    ]
