# Generated by Django 3.2.8 on 2021-12-18 09:43

import Location.snippets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=Location.snippets.name_of_file, verbose_name='Иконки')),
            ],
        ),
        migrations.CreateModel(
            name='CommonLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=Location.snippets.name_of_file, verbose_name='Картинки для локации')),
            ],
        ),
    ]
