# Generated by Django 3.2.8 on 2021-12-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonicon',
            options={'verbose_name_plural': 'Общие иконки'},
        ),
        migrations.AlterModelOptions(
            name='commonlogo',
            options={'verbose_name_plural': 'Лого'},
        ),
        migrations.RenameField(
            model_name='commonicon',
            old_name='logo',
            new_name='icon',
        ),
    ]
