# Generated by Django 3.2.8 on 2021-12-20 21:06

import Location.snippets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0003_commonicon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.ImageField(upload_to=Location.snippets.name_of_file, verbose_name='Темп фото')),
            ],
        ),
    ]
