# Generated by Django 3.2.8 on 2021-10-26 18:14

import Location.snippets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Location.snippets.name_of_file, verbose_name='Картинка для Рекламы')),
                ('link', models.CharField(max_length=255, verbose_name='Линк для рекламы')),
            ],
            options={
                'verbose_name_plural': 'Реклама',
            },
        ),
    ]
