# Generated by Django 3.2.8 on 2022-05-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_reset_validate',
            field=models.BooleanField(default=False),
        ),
    ]
