# Generated by Django 3.2.8 on 2022-01-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confidential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('body', models.TextField(verbose_name='Описание правил')),
            ],
            options={
                'verbose_name_plural': 'Правила конфидециальности',
            },
        ),
    ]
