# Generated by Django 3.2.8 on 2022-07-01 02:39

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('confidentialApp', '0003_instructions'),
    ]

    operations = [

        migrations.CreateModel(
            name='Instructions',
           fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('body', models.TextField(verbose_name='Описание правил')),
            ],
            options={
                'verbose_name_plural': 'Инструкции',
            },
        ),
           migrations.CreateModel(
            name='SaleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('body', models.TextField(verbose_name='Описание правил')),
            ],
            options={
                'verbose_name_plural': 'Правила покупки услуг',
            },
        ),
    ]
