# Generated by Django 3.2.8 on 2021-10-26 18:16

import Location.snippets
from django.db import migrations, models
import django.db.models.deletion
import django_admin_geomap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialistApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=Location.snippets.name_of_file, verbose_name='Картинки для локации')),
            ],
            options={
                'verbose_name_plural': 'Фото для локации',
            },
        ),
        migrations.CreateModel(
            name='LocationCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Страна',
            },
        ),
        migrations.CreateModel(
            name='LocationCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationApp.locationcountry', verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Локация активна')),
                ('district', models.CharField(max_length=150, verbose_name='Район')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('category', models.ManyToManyField(to='specialistApp.Category', verbose_name='Вид деятельности локации')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationApp.locationcity', verbose_name='Город')),
                ('images', models.ManyToManyField(to='locationApp.Images', verbose_name='Картинки для локации')),
            ],
            options={
                'verbose_name_plural': 'Локации',
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
