# Generated by Django 3.2.8 on 2021-10-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
