# Generated by Django 3.2.8 on 2021-11-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0002_auto_20211026_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
    ]
