# Generated by Django 3.2.8 on 2021-11-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0003_remove_location_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='comfort',
            field=models.TextField(default='asdsad', max_length=300, verbose_name='Удобства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='function_less',
            field=models.BooleanField(default=False, verbose_name='доступность малообильных людей'),
        ),
        migrations.AddField(
            model_name='location',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
    ]
