# Generated by Django 3.2.8 on 2022-02-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0006_alter_specialist_description'),
        ('locationApp', '0008_alter_images_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category_location',
            field=models.ManyToManyField(default=[], to='specialistApp.Category', verbose_name='Виды деятельности локации'),
        ),
    ]
