# Generated by Django 3.2.8 on 2022-08-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='days',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
